### ISSUE TITLE
fps

### ISSUE THREAD

**Issue by p8nts** [WaffleManTheGreat/DirtyFork#4]
the bypass script really messing with fps even with antilag

**Comment by WaffleManTheGreat** [comment]
Hmmmm
I Will See If i can make it less laggy

**Comment by WaffleManTheGreat** [comment]
I have just fixed the bypass! Thank you for this report.
The issue was constant loops running a iv in pairs script.
I have replaced this for PlayerAdded()
There is also now a Resetting double check for the bypass so you dont have anymore
issues with esp/aimbot not working after a while.

Please continue to create these issue reports as it helps me develop.

If you are continuing to have issues with fps please refrain from using the old silent aim- as it effects fps heavily.
I am currently working on a fix.

**Comment by p8nts** [comment]
thanks, love the script

**Comment by WaffleManTheGreat** [comment]
thanks :) @
